# Copyright IBM Corp. 2016, 2025
# SPDX-License-Identifier: BUSL-1.1


# This action will set up Node and then install pnpm dependencies, which might be restored from cache if available.
# In case of a cache miss, pnpm dependencies will be installed and later be stored in the "post step" of actions/cache.
---
name: Setup pnpm
description: Setup Node and install pnpm
runs:
  using: composite
  steps:

    - name: Install PNPM
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false
        package_json_file: './ui/package.json'

    - name: Setup Node Caching
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: './ui/package.json'
        cache: pnpm
        cache-dependency-path: ui/pnpm-lock.yaml

    - name: Install UI dependencies
      working-directory: ./ui
      shell: bash
      run: |
        pnpm i
        pnpm rebuild node-sass
